#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Multi-run hypertension classification with custom All/Day/Night prediction thresholds.

This script is a practical replacement for bp_htn_classification_multi_run.py when
threshold grid search has produced different prediction thresholds for All/Day/Night.

Default true-label thresholds:
  All   true: 130/80
  Day   true: 135/85  (sleep == 0)
  Night true: 120/70  (sleep == 1)

Prediction thresholds default to the same values, but can be overridden:
  --pred-all-sbp / --pred-all-dbp
  --pred-day-sbp / --pred-day-dbp
  --pred-night-sbp / --pred-night-dbp

It also supports reading thresholds from threshold_grid_best_by_split.csv generated by
the threshold grid-search script. That file should contain:
  method, split, pred_sbp_thr, pred_dbp_thr

Combined rule:
  true_combined = true_all OR true_day OR true_night
  pred_combined = pred_all OR pred_day OR pred_night

Examples:

# Use manual custom thresholds for bias method
python bp_htn_classification_multi_run_custom_thresholds.py \
  --csv-glob "eval_1p0_sensitivity/predictions_*.csv" \
  --methods bias \
  --true-sbp-col ABPM_SBP --true-dbp-col ABPM_DBP \
  --pred-all-sbp 131 --pred-all-dbp 80 \
  --pred-day-sbp 134 --pred-day-dbp 82 \
  --pred-night-sbp 128 --pred-night-dbp 74 \
  --out-dir eval_1p0_sensitivity/classification_custom_thr

# Load thresholds from grid-search output
python bp_htn_classification_multi_run_custom_thresholds.py \
  --csv-glob "eval_1p0_sensitivity/predictions_*.csv" \
  --methods bias \
  --threshold-csv threshold_search/threshold_grid_best_by_split.csv \
  --out-dir eval_1p0_sensitivity/classification_from_grid
"""

from __future__ import annotations

import argparse
import glob
import json
from dataclasses import dataclass, asdict
from pathlib import Path
from typing import Any, Dict, List, Optional, Sequence, Tuple

import numpy as np
import pandas as pd

TRUEY = {"1", "true", "yes", "y", "t"}


@dataclass(frozen=True)
class Threshold:
    sbp: float
    dbp: float


METHOD_TO_COLS: Dict[str, Tuple[str, str]] = {
    "raw": ("y_pred_sbp_raw", "y_pred_dbp_raw"),
    "bias": ("y_pred_sbp_bias", "y_pred_dbp_bias"),
    "aff": ("y_pred_sbp_aff", "y_pred_dbp_aff"),
    "bank": ("y_pred_sbp_bank", "y_pred_dbp_bank"),
    "cal": ("y_pred_sbp_cal", "y_pred_dbp_cal"),
}


def parse_bool_series(s: pd.Series) -> pd.Series:
    if s.dtype == bool:
        return s
    return s.astype(str).str.strip().str.lower().isin(TRUEY)


def safe_div(num: float, den: float) -> float:
    return 0.0 if den == 0 else float(num) / float(den)


def is_positive(sbp: float, dbp: float, thr: Threshold) -> bool:
    return (float(sbp) >= float(thr.sbp)) or (float(dbp) >= float(thr.dbp))


def confusion(y_true: Sequence[bool], y_pred: Sequence[bool]) -> Dict[str, Any]:
    y_true = np.asarray(y_true, dtype=bool)
    y_pred = np.asarray(y_pred, dtype=bool)

    tp = int(np.sum(y_true & y_pred))
    tn = int(np.sum((~y_true) & (~y_pred)))
    fp = int(np.sum((~y_true) & y_pred))
    fn = int(np.sum(y_true & (~y_pred)))

    precision = safe_div(tp, tp + fp)
    recall = safe_div(tp, tp + fn)
    specificity = safe_div(tn, tn + fp)
    accuracy = safe_div(tp + tn, tp + tn + fp + fn)
    f1 = safe_div(2 * precision * recall, precision + recall)

    return {
        "tp": tp,
        "tn": tn,
        "fp": fp,
        "fn": fn,
        "precision": precision,
        "recall": recall,
        "sensitivity": recall,
        "specificity": specificity,
        "accuracy": accuracy,
        "f1": f1,
    }


def method_name(method: str) -> str:
    if ":" in method:
        return method.split(":")[0]
    return method


def resolve_method_cols(method: str, df: pd.DataFrame) -> Tuple[str, str]:
    """
    Supports:
      bias
      aff
      bank
      custom_name:pred_sbp_col:pred_dbp_col
    """
    method = method.strip()
    if ":" in method:
        parts = method.split(":")
        if len(parts) != 3:
            raise ValueError(
                "Custom method should be name:pred_sbp_col:pred_dbp_col, "
                f"got {method}"
            )
        sbp_col, dbp_col = parts[1], parts[2]
    else:
        if method not in METHOD_TO_COLS:
            raise ValueError(f"Unknown method={method}; valid={list(METHOD_TO_COLS)}")
        sbp_col, dbp_col = METHOD_TO_COLS[method]

    missing = [c for c in [sbp_col, dbp_col] if c not in df.columns]
    if missing:
        raise ValueError(
            f"Missing prediction columns for method={method}: {missing}. "
            f"Available columns include: {list(df.columns)[:30]}"
        )
    return sbp_col, dbp_col


def filter_split(df: pd.DataFrame, split: str, sleep_col: str) -> pd.DataFrame:
    if split == "all":
        return df
    if split == "day":
        return df[pd.to_numeric(df[sleep_col], errors="coerce").fillna(0).astype(int) == 0]
    if split == "night":
        return df[pd.to_numeric(df[sleep_col], errors="coerce").fillna(0).astype(int) == 1]
    raise ValueError(f"Unknown split={split}")


def prepare_df(
    df: pd.DataFrame,
    include_calib: bool,
    is_calib_col: str,
) -> pd.DataFrame:
    out = df.copy()
    if not include_calib and is_calib_col in out.columns:
        out = out[~parse_bool_series(out[is_calib_col])].copy()
    return out


def collect_valid(
    df: pd.DataFrame,
    split: str,
    subject_col: str,
    sleep_col: str,
    true_sbp_col: str,
    true_dbp_col: str,
    pred_sbp_col: str,
    pred_dbp_col: str,
) -> pd.DataFrame:
    d = filter_split(df, split, sleep_col).copy()
    required = [subject_col, true_sbp_col, true_dbp_col, pred_sbp_col, pred_dbp_col]
    miss = [c for c in required if c not in d.columns]
    if miss:
        raise ValueError(f"Missing required columns: {miss}")

    for c in [true_sbp_col, true_dbp_col, pred_sbp_col, pred_dbp_col]:
        d[c] = pd.to_numeric(d[c], errors="coerce")

    d = d.dropna(subset=[subject_col, true_sbp_col, true_dbp_col, pred_sbp_col, pred_dbp_col])
    return d


def compute_subject_metrics(
    df: pd.DataFrame,
    split: str,
    true_thr: Threshold,
    pred_thr: Threshold,
    subject_col: str,
    sleep_col: str,
    true_sbp_col: str,
    true_dbp_col: str,
    pred_sbp_col: str,
    pred_dbp_col: str,
) -> Tuple[Dict[str, Any], Dict[str, Tuple[bool, bool, int]]]:
    d = collect_valid(df, split, subject_col, sleep_col, true_sbp_col, true_dbp_col, pred_sbp_col, pred_dbp_col)
    y_true: List[bool] = []
    y_pred: List[bool] = []
    labels: Dict[str, Tuple[bool, bool, int]] = {}

    for sid, g in d.groupby(subject_col, sort=False):
        true_sbp = float(g[true_sbp_col].mean())
        true_dbp = float(g[true_dbp_col].mean())
        pred_sbp = float(g[pred_sbp_col].mean())
        pred_dbp = float(g[pred_dbp_col].mean())
        t = is_positive(true_sbp, true_dbp, true_thr)
        p = is_positive(pred_sbp, pred_dbp, pred_thr)
        y_true.append(t)
        y_pred.append(p)
        labels[str(sid)] = (t, p, int(len(g)))

    m = confusion(y_true, y_pred)
    m.update({"n_rows": int(len(d)), "n_subjects": int(len(y_true)), "mode": "subject"})
    return m, labels


def compute_micro_metrics(
    df: pd.DataFrame,
    split: str,
    true_thr: Threshold,
    pred_thr: Threshold,
    subject_col: str,
    sleep_col: str,
    true_sbp_col: str,
    true_dbp_col: str,
    pred_sbp_col: str,
    pred_dbp_col: str,
) -> Dict[str, Any]:
    d = collect_valid(df, split, subject_col, sleep_col, true_sbp_col, true_dbp_col, pred_sbp_col, pred_dbp_col)
    y_true = [is_positive(r[true_sbp_col], r[true_dbp_col], true_thr) for _, r in d.iterrows()]
    y_pred = [is_positive(r[pred_sbp_col], r[pred_dbp_col], pred_thr) for _, r in d.iterrows()]
    m = confusion(y_true, y_pred)
    m.update({"n_rows": int(len(d)), "n_subjects": int(d[subject_col].nunique()), "mode": "micro"})
    return m


def compute_macro_metrics(
    df: pd.DataFrame,
    split: str,
    true_thr: Threshold,
    pred_thr: Threshold,
    subject_col: str,
    sleep_col: str,
    true_sbp_col: str,
    true_dbp_col: str,
    pred_sbp_col: str,
    pred_dbp_col: str,
) -> Dict[str, Any]:
    d = collect_valid(df, split, subject_col, sleep_col, true_sbp_col, true_dbp_col, pred_sbp_col, pred_dbp_col)

    total_true: List[bool] = []
    total_pred: List[bool] = []
    per_subject: List[Dict[str, Any]] = []

    for _, g in d.groupby(subject_col, sort=False):
        y_true = [is_positive(r[true_sbp_col], r[true_dbp_col], true_thr) for _, r in g.iterrows()]
        y_pred = [is_positive(r[pred_sbp_col], r[pred_dbp_col], pred_thr) for _, r in g.iterrows()]
        total_true.extend(y_true)
        total_pred.extend(y_pred)
        per_subject.append(confusion(y_true, y_pred))

    total = confusion(total_true, total_pred)
    if per_subject:
        for k in ["precision", "recall", "sensitivity", "specificity", "accuracy", "f1"]:
            total[k] = float(np.mean([x[k] for x in per_subject]))

    total.update({"n_rows": int(len(d)), "n_subjects": int(d[subject_col].nunique()), "mode": "macro"})
    return total


def compute_split_metrics(
    df: pd.DataFrame,
    split: str,
    average: str,
    true_thr: Threshold,
    pred_thr: Threshold,
    subject_col: str,
    sleep_col: str,
    true_sbp_col: str,
    true_dbp_col: str,
    pred_sbp_col: str,
    pred_dbp_col: str,
) -> Tuple[Dict[str, Any], Optional[Dict[str, Tuple[bool, bool, int]]]]:
    if average == "subject":
        return compute_subject_metrics(df, split, true_thr, pred_thr, subject_col, sleep_col, true_sbp_col, true_dbp_col, pred_sbp_col, pred_dbp_col)
    if average == "micro":
        return compute_micro_metrics(df, split, true_thr, pred_thr, subject_col, sleep_col, true_sbp_col, true_dbp_col, pred_sbp_col, pred_dbp_col), None
    if average == "macro":
        return compute_macro_metrics(df, split, true_thr, pred_thr, subject_col, sleep_col, true_sbp_col, true_dbp_col, pred_sbp_col, pred_dbp_col), None
    raise ValueError(f"Unknown average={average}")


def compute_combined_from_subject_labels(
    split_labels: Dict[str, Dict[str, Tuple[bool, bool, int]]]
) -> Dict[str, Any]:
    subject_ids = set()
    for labels in split_labels.values():
        subject_ids.update(labels.keys())

    y_true: List[bool] = []
    y_pred: List[bool] = []
    n_rows = 0

    for sid in sorted(subject_ids):
        t = False
        p = False
        for split in ["all", "day", "night"]:
            if sid in split_labels.get(split, {}):
                tt, pp, nn = split_labels[split][sid]
                t = t or tt
                p = p or pp
                n_rows += int(nn)
        y_true.append(t)
        y_pred.append(p)

    m = confusion(y_true, y_pred)
    m.update({"n_rows": int(n_rows), "n_subjects": int(len(subject_ids)), "mode": "subject"})
    return m


# =============================================================================
# Thresholds
# =============================================================================

def build_true_thresholds(args: argparse.Namespace) -> Dict[str, Threshold]:
    return {
        "all": Threshold(args.true_all_sbp, args.true_all_dbp),
        "day": Threshold(args.true_day_sbp, args.true_day_dbp),
        "night": Threshold(args.true_night_sbp, args.true_night_dbp),
    }


def build_cli_pred_thresholds(args: argparse.Namespace) -> Dict[str, Threshold]:
    true_thr = build_true_thresholds(args)

    def get(split: str, sbp: Optional[float], dbp: Optional[float]) -> Threshold:
        return Threshold(
            true_thr[split].sbp if sbp is None else float(sbp),
            true_thr[split].dbp if dbp is None else float(dbp),
        )

    return {
        "all": get("all", args.pred_all_sbp, args.pred_all_dbp),
        "day": get("day", args.pred_day_sbp, args.pred_day_dbp),
        "night": get("night", args.pred_night_sbp, args.pred_night_dbp),
    }


def load_threshold_csv(path: Optional[str]) -> Dict[Tuple[str, str], Threshold]:
    if path is None:
        return {}
    p = Path(path)
    if not p.exists():
        raise FileNotFoundError(f"threshold csv not found: {path}")
    df = pd.read_csv(p)
    required = ["method", "split", "pred_sbp_thr", "pred_dbp_thr"]
    miss = [c for c in required if c not in df.columns]
    if miss:
        raise ValueError(f"threshold csv missing columns: {miss}")

    out: Dict[Tuple[str, str], Threshold] = {}
    for _, r in df.iterrows():
        method = str(r["method"])
        split = str(r["split"])
        if split not in {"all", "day", "night"}:
            continue
        out[(method, split)] = Threshold(float(r["pred_sbp_thr"]), float(r["pred_dbp_thr"]))
    return out


def get_pred_thr(method: str, split: str, cli_pred: Dict[str, Threshold], loaded: Dict[Tuple[str, str], Threshold]) -> Threshold:
    m = method_name(method)
    if (m, split) in loaded:
        return loaded[(m, split)]
    # Compatibility with sleep-shrinkage grid script.
    if m == "bias" and ("bias_sleep_shrink", split) in loaded:
        return loaded[("bias_sleep_shrink", split)]
    return cli_pred[split]


# =============================================================================
# Multi-run
# =============================================================================

def evaluate_one_csv(
    path: Path,
    run_id: int,
    methods: List[str],
    average: str,
    true_sbp_col: str,
    true_dbp_col: str,
    subject_col: str,
    sleep_col: str,
    is_calib_col: str,
    include_calib: bool,
    true_thresholds: Dict[str, Threshold],
    cli_pred_thresholds: Dict[str, Threshold],
    loaded_thresholds: Dict[Tuple[str, str], Threshold],
    include_combined: bool,
) -> List[Dict[str, Any]]:
    df0 = pd.read_csv(path)
    df = prepare_df(df0, include_calib=include_calib, is_calib_col=is_calib_col)

    rows: List[Dict[str, Any]] = []
    for method in methods:
        pred_sbp_col, pred_dbp_col = resolve_method_cols(method, df)
        split_labels: Dict[str, Dict[str, Tuple[bool, bool, int]]] = {}

        for split in ["all", "day", "night"]:
            true_thr = true_thresholds[split]
            pred_thr = get_pred_thr(method, split, cli_pred_thresholds, loaded_thresholds)
            m, labels = compute_split_metrics(
                df=df,
                split=split,
                average=average,
                true_thr=true_thr,
                pred_thr=pred_thr,
                subject_col=subject_col,
                sleep_col=sleep_col,
                true_sbp_col=true_sbp_col,
                true_dbp_col=true_dbp_col,
                pred_sbp_col=pred_sbp_col,
                pred_dbp_col=pred_dbp_col,
            )
            if labels is not None:
                split_labels[split] = labels

            row = {
                "run_id": run_id,
                "csv_path": str(path),
                "method": method_name(method),
                "split": split,
                "mode": m.pop("mode"),
                "true_sbp_thr": true_thr.sbp,
                "true_dbp_thr": true_thr.dbp,
                "pred_sbp_thr": pred_thr.sbp,
                "pred_dbp_thr": pred_thr.dbp,
                "true_sbp_col": true_sbp_col,
                "true_dbp_col": true_dbp_col,
                "pred_sbp_col": pred_sbp_col,
                "pred_dbp_col": pred_dbp_col,
            }
            row.update(m)
            rows.append(row)

        if include_combined:
            # Combined is product-level subject OR. It is only meaningful from subject-level split labels.
            # Even if average=micro/macro, we recompute subject-level labels for combined.
            if average != "subject" or len(split_labels) < 3:
                split_labels = {}
                for split in ["all", "day", "night"]:
                    true_thr = true_thresholds[split]
                    pred_thr = get_pred_thr(method, split, cli_pred_thresholds, loaded_thresholds)
                    _, labels = compute_subject_metrics(
                        df=df,
                        split=split,
                        true_thr=true_thr,
                        pred_thr=pred_thr,
                        subject_col=subject_col,
                        sleep_col=sleep_col,
                        true_sbp_col=true_sbp_col,
                        true_dbp_col=true_dbp_col,
                        pred_sbp_col=pred_sbp_col,
                        pred_dbp_col=pred_dbp_col,
                    )
                    split_labels[split] = labels

            m = compute_combined_from_subject_labels(split_labels)
            row = {
                "run_id": run_id,
                "csv_path": str(path),
                "method": method_name(method),
                "split": "combined",
                "mode": m.pop("mode"),
                "true_sbp_thr": np.nan,
                "true_dbp_thr": np.nan,
                "pred_sbp_thr": np.nan,
                "pred_dbp_thr": np.nan,
                "true_sbp_col": true_sbp_col,
                "true_dbp_col": true_dbp_col,
                "pred_sbp_col": pred_sbp_col,
                "pred_dbp_col": pred_dbp_col,
            }
            row.update(m)
            rows.append(row)

    return rows


def summarize_across_runs(per_run: pd.DataFrame) -> pd.DataFrame:
    group_cols = ["method", "split", "mode", "true_sbp_thr", "true_dbp_thr", "pred_sbp_thr", "pred_dbp_thr"]
    metric_cols = ["n_rows", "n_subjects", "tp", "tn", "fp", "fn", "precision", "recall", "sensitivity", "specificity", "accuracy", "f1"]

    rows: List[Dict[str, Any]] = []
    for keys, g in per_run.groupby(group_cols, dropna=False, sort=False):
        if not isinstance(keys, tuple):
            keys = (keys,)
        row = {k: v for k, v in zip(group_cols, keys)}
        row["n_runs"] = int(g["run_id"].nunique())
        for col in metric_cols:
            x = pd.to_numeric(g[col], errors="coerce").dropna().to_numpy(dtype=float)
            if len(x) == 0:
                row[f"{col}_mean"] = np.nan
                row[f"{col}_std_across_runs"] = np.nan
                row[f"{col}_min"] = np.nan
                row[f"{col}_max"] = np.nan
            else:
                row[f"{col}_mean"] = float(np.mean(x))
                row[f"{col}_std_across_runs"] = float(np.std(x, ddof=1)) if len(x) > 1 else np.nan
                row[f"{col}_min"] = float(np.min(x))
                row[f"{col}_max"] = float(np.max(x))
        rows.append(row)
    return pd.DataFrame(rows)


def pooled_confusion(per_run: pd.DataFrame) -> pd.DataFrame:
    group_cols = ["method", "split", "mode", "true_sbp_thr", "true_dbp_thr", "pred_sbp_thr", "pred_dbp_thr"]
    rows: List[Dict[str, Any]] = []
    for keys, g in per_run.groupby(group_cols, dropna=False, sort=False):
        if not isinstance(keys, tuple):
            keys = (keys,)
        row = {k: v for k, v in zip(group_cols, keys)}
        tp = int(pd.to_numeric(g["tp"], errors="coerce").fillna(0).sum())
        tn = int(pd.to_numeric(g["tn"], errors="coerce").fillna(0).sum())
        fp = int(pd.to_numeric(g["fp"], errors="coerce").fillna(0).sum())
        fn = int(pd.to_numeric(g["fn"], errors="coerce").fillna(0).sum())
        m = confusion([True] * tp + [False] * fp + [False] * tn + [True] * fn,
                      [True] * tp + [True] * fp + [False] * tn + [False] * fn)
        row.update({
            "tp_sum": tp,
            "tn_sum": tn,
            "fp_sum": fp,
            "fn_sum": fn,
            "sensitivity_pooled": m["sensitivity"],
            "specificity_pooled": m["specificity"],
            "accuracy_pooled": m["accuracy"],
            "precision_pooled": m["precision"],
            "f1_pooled": m["f1"],
        })
        rows.append(row)
    return pd.DataFrame(rows)


def parse_methods(s: str) -> List[str]:
    return [x.strip() for x in s.split(",") if x.strip()]


def resolve_paths(positional: List[str], csv_glob: Optional[str]) -> List[Path]:
    paths: List[Path] = []
    if csv_glob:
        paths.extend(Path(p) for p in sorted(glob.glob(csv_glob)))
    paths.extend(Path(p) for p in positional)
    seen = set()
    out: List[Path] = []
    for p in paths:
        key = str(p)
        if key not in seen:
            out.append(p)
            seen.add(key)
    if not out:
        raise FileNotFoundError("No CSV files provided. Use --csv-glob or positional csv paths.")
    missing = [str(p) for p in out if not p.exists()]
    if missing:
        raise FileNotFoundError(f"Missing CSV files: {missing[:5]}")
    return out


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(
        description="Multi-run hypertension classification with custom prediction thresholds for All/Day/Night."
    )
    p.add_argument("csv_paths", nargs="*", help="Input CSV paths. You can also use --csv-glob.")
    p.add_argument("--csv-glob", default=None, help="Glob pattern for multiple prediction CSVs.")
    p.add_argument("--out-dir", default="classification_custom_thresholds")
    p.add_argument("--methods", default="bias", help="Comma-separated: raw,bias,aff,bank,cal or custom name:sbp_col:dbp_col")

    p.add_argument("--true-sbp-col", default="ABPM_SBP")
    p.add_argument("--true-dbp-col", default="ABPM_DBP")
    p.add_argument("--subject-col", default="id_clean")
    p.add_argument("--sleep-col", default="sleep")
    p.add_argument("--is-calib-col", default="is_calib")
    p.add_argument("--include-calib", action="store_true", help="Include calibration rows. Default: exclude.")
    p.add_argument("--average", choices=["subject", "micro", "macro"], default="subject")

    # True thresholds.
    p.add_argument("--true-all-sbp", type=float, default=130.0)
    p.add_argument("--true-all-dbp", type=float, default=80.0)
    p.add_argument("--true-day-sbp", type=float, default=135.0)
    p.add_argument("--true-day-dbp", type=float, default=85.0)
    p.add_argument("--true-night-sbp", type=float, default=120.0)
    p.add_argument("--true-night-dbp", type=float, default=70.0)

    # Prediction thresholds; default to true thresholds if omitted.
    p.add_argument("--pred-all-sbp", type=float, default=None)
    p.add_argument("--pred-all-dbp", type=float, default=None)
    p.add_argument("--pred-day-sbp", type=float, default=None)
    p.add_argument("--pred-day-dbp", type=float, default=None)
    p.add_argument("--pred-night-sbp", type=float, default=None)
    p.add_argument("--pred-night-dbp", type=float, default=None)

    p.add_argument("--threshold-csv", default=None, help="Optional threshold_grid_best_by_split.csv from grid search.")
    p.add_argument("--no-combined", action="store_true")
    return p.parse_args()


def main() -> None:
    args = parse_args()
    csv_paths = resolve_paths(args.csv_paths, args.csv_glob)
    methods = parse_methods(args.methods)
    out_dir = Path(args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    true_thresholds = build_true_thresholds(args)
    cli_pred_thresholds = build_cli_pred_thresholds(args)
    loaded_thresholds = load_threshold_csv(args.threshold_csv)

    all_rows: List[Dict[str, Any]] = []
    for run_id, p in enumerate(csv_paths):
        rows = evaluate_one_csv(
            path=p,
            run_id=run_id,
            methods=methods,
            average=args.average,
            true_sbp_col=args.true_sbp_col,
            true_dbp_col=args.true_dbp_col,
            subject_col=args.subject_col,
            sleep_col=args.sleep_col,
            is_calib_col=args.is_calib_col,
            include_calib=args.include_calib,
            true_thresholds=true_thresholds,
            cli_pred_thresholds=cli_pred_thresholds,
            loaded_thresholds=loaded_thresholds,
            include_combined=not args.no_combined,
        )
        all_rows.extend(rows)

    per_run = pd.DataFrame(all_rows)
    summary = summarize_across_runs(per_run)
    pooled = pooled_confusion(per_run)

    per_run_path = out_dir / "htn_classification_per_run.csv"
    summary_path = out_dir / "htn_classification_mean_std_across_runs.csv"
    pooled_path = out_dir / "htn_classification_pooled_confusion.csv"
    manifest_path = out_dir / "htn_classification_manifest.json"

    per_run.to_csv(per_run_path, index=False)
    summary.to_csv(summary_path, index=False)
    pooled.to_csv(pooled_path, index=False)

    manifest = {
        "csv_paths": [str(p) for p in csv_paths],
        "n_csv": len(csv_paths),
        "methods": methods,
        "average": args.average,
        "true_sbp_col": args.true_sbp_col,
        "true_dbp_col": args.true_dbp_col,
        "include_calib": bool(args.include_calib),
        "true_thresholds": {k: asdict(v) for k, v in true_thresholds.items()},
        "cli_pred_thresholds": {k: asdict(v) for k, v in cli_pred_thresholds.items()},
        "threshold_csv": args.threshold_csv,
        "loaded_thresholds": {f"{k[0]}::{k[1]}": asdict(v) for k, v in loaded_thresholds.items()},
        "combined": not args.no_combined,
        "outputs": {
            "per_run": str(per_run_path),
            "summary": str(summary_path),
            "pooled": str(pooled_path),
        },
    }
    with open(manifest_path, "w", encoding="utf-8") as f:
        json.dump(manifest, f, indent=2, ensure_ascii=False)

    compact_cols = [
        "method", "split", "mode",
        "true_sbp_thr", "true_dbp_thr", "pred_sbp_thr", "pred_dbp_thr",
        "sensitivity_mean", "specificity_mean", "accuracy_mean", "f1_mean",
        "sensitivity_std_across_runs", "specificity_std_across_runs",
    ]
    print("\n=== Classification summary ===")
    print(summary[[c for c in compact_cols if c in summary.columns]].to_string(index=False))
    print("\nSaved:")
    print(f"  {per_run_path}")
    print(f"  {summary_path}")
    print(f"  {pooled_path}")


if __name__ == "__main__":
    main()
